Python编程-从入门到实践/Web应用程序/learning_log/learning_log/urls.py
from django.contrib import admin
from django.conf.urls import include,url

urlpatterns = [
    url(r'^admin/',include(admin.site.urls)),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'',include('learning_logs.urls',namespace='learning_logs')),
]

Python编程-从入门到实践/Web应用程序/learning_log/learning_logs/urls.py
'''定义learning_logs的URL模式'''

from django.conf.urls import url
from  . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index,name='index'),

    # 显示所有的主题
    url(r'topics/$', views.topics,name='topics'),
    # 显示特定主题的详细信息
    url(r'topics/(?P<topic_id>\d+)/$', views.topic,name='topic'),
    # 用于添加新主题的网页
    url(r'^new_topic/$',views.new_topic,name='new_topic'),
    # 用于添加新条目的界面
    url(r'^new_entry/(?P<topic_id>\d+)/$',views.new_entry,name='new_entry'),
    # 用于编辑条目的页面
    url(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name='edit_entry'),
]

Python编程-从入门到实践/Web应用程序/learning_log/users/urls.py
'''为应用程序users定义URL模式'''
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
    # 登录界面
    url(r'^login/$',login,{'template_name':'users/login.html'},
        name='login'),
    # 注销
    url(r'^logout/$',views.logout_view,name='logout'),
    # 注册页面
    url(r'^register/$', views.register, name='register'),
]

Python编程-从入门到实践/Web应用程序/learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic (models.Model):
    '''用户学习的主题'''
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        '''返回模型的字符串表示'''
        return self.text

class Entry(models.Model):
    '''学习的有关某一个主题的具体知识'''
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        '''返回模型的字符串表示'''
        return self.text[:50]+'...'

Python编程-从入门到实践/Web应用程序/learning_log/users/models.py
from django.db import models

# Create your models here.

Python编程-从入门到实践/Web应用程序/learning_log/learning_logs/forms.py
from django import forms

from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

Python编程-从入门到实践/Web应用程序/learning_log/learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,Http404
from django.core.urlresolvers import reverse
from .models import Topic,Entry
from .forms import TopicForm,EntryForm
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    '''学习笔记的主页'''
    return render(request,'learning_logs/index.html')

@login_required
def topic(request,topic_id):
    '''显示单个主题及其所有的条目'''
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于当前用户
    if topic.owner !=request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)

@login_required
def topics(request):
    '''显示所有的主题'''
    topics = Topic.objects.filter(ownwe=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request,'learning_logs/topics.html',context)

@login_required
def new_topic(request):
    '''添加新主题'''
    if request.method !='POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()
    else:
        # POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form':form}
    return render(request,'learning_logs/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
    '''特定的主题中添加新条目'''
    topic = Topic.objects.get(id=topic_id)

    if request.method !='POST':
        form = EntryForm()
    else:
        # POST提交的数据，对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic_id]))
    context = {'topic':topic,'form':form,}
    return render(request,'learning_logs/new_entry.html',context)

@login_required
def edit_entry(request,entry_id):
    '''编辑既有条目'''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner !=request.user:
        raise Http404

    if request.method !='POST':
        # 初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic.id]))
    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)

Python编程-从入门到实践/Web应用程序/learning_log/users/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.contrib.auth import logout,login,authenticate
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserChangeForm


def logout_view(request):
    '''注销用户'''
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    '''注册新用户'''
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserChangeForm()
    else:
        # 处理填写好的表单
        form = UserChangeForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重新定向到主页
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request,authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form':form}
    return render(request,'users/register.html',context)
# Create your views here.

Python编程-从入门到实践/Web应用程序/learning_log/learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a>
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
    {% if users.is_authenticated %}
        Hello,{{ user.username }}.
        <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">register</a>
        <a href="{% url 'users:login' %}">log in</a>
    {% endif %}

</p>

{% block content %}{% endblock content%}

Python编程-从入门到实践/Web应用程序/learning_log/learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
    {% extends "learning_logs/base.html" %}

    {% block content %}

        <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

        <p>Edit entry:</p>

        <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">save changes</button>
        </form>

    {% endblock content %}

Python编程-从入门到实践/Web应用程序/learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html"%}

{% block content%}

    <p>Learning Log helps you keep track of your learning,for any topic you're
learning about.</p>
{% endblock content%}

Python编程-从入门到实践/Web应用程序/learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add a new entry:</p>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add entry</button>
    </form>

{% endblock content %}

Python编程-从入门到实践/Web应用程序/learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p>Add a new topic:</p>

    <form action="{% url 'learning_logs:new_topic' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add topic</button>
    </form>

{% endblock content %}

Python编程-从入门到实践/Web应用程序/learning_log/learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
    {% extends "learning_logs/base.html" %}

    {% block content %}
        <p>Topic:{ {topic} }</p>

        <p>Entries</p>

        <p>
            <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
        </p>

        <ul>
        {% for entry in entries %}
            <li>
                <p>{{ entry.date_added|date:'M d,Y H:i' }}</p>
                <p>{{ entry.text|linebreaks }}</p>
                <p>
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
                </p>
            </li>
        {% empty %}
                <li>
                    There are no ertries for this topic yet.
                </li>
        {% endfor %}
        </ul>


    {% endblock content %}

Python编程-从入门到实践/Web应用程序/learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p>Topic:{ {topic} }</p>

    <p>Topics</p>

    <ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </li>
    {% empty %}
            <li>
                There are no ertries for this topic yet.
            </li>
    {% endfor %}
    </ul>

    <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock content %}

Python编程-从入门到实践/Web应用程序/learning_log/users/templates/users/login.html
{% extends "learning_logs/base.html" %}

{% block content %}
    {% if form.errors %}
    <p>Your username and password didn't match. Plasd try again</p>
    {% endif %}

    <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">log in</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %}

Python编程-从入门到实践/Web应用程序/learning_log/users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>
{% extends "learning_logs/base.html" %}

{% block content %}
    <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %}